### ISSUE TITLE
remote Permission to jlord/patchwork.git denied  returned error: 403

### ISSUE THREAD

**Issue by tariik** [jlord/patchwork#11600]
remote: Permission to jlord/patchwork.git denied to tariik.
fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403 me, @jlord. If you don't delete these lines then it'll be done for you :smile: thanks!

**Comment by jlord** [comment]
It's unclear what you're referring to here, could you elaborate please?

**Comment by dbwebconsulting** [comment]
I am getting the same error when I try to do the 'Branches Aren't Just For Birds' step in Git-it. I'm trying to do a push to the contributors directory. IE: git push origin add-dbwebconsulting. I'm on a pc, win 7. 64bit. My git config origin url is: url = https://github.com/jlord/patchwork.git/. I am getting the following error:
Found branch as expected!
Error: Command failed: "H:\UserFiles\Web-stuff\Git-it-win32-ia32\resources\app\assets\PortableGit\bin\git.exe " reflog show origin/add-dbwebconsulting fatal: ambiguous argument 'origin/add-dbwebconsulting': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'

**Comment by ghost** [comment]
I'm having the same issue working on a Mac. I feel I have a pretty good sense of git but not sure what the problem is.

**Comment by jlord** [comment]
When you get a 403 on this challenge it is because you are trying to push your changes to a repository you don't have access to i.e. my original one `jlord/patchwork`.

I'm going to update the app soon to make it more clear since this is catching quite a few people. 

To see what your remotes are you can run:

``` bash
git remote -v
```

You should have an `origin` that points to the copy (fork) on _your_ GitHub account and one named `upstream` that points to my original `jlord/patchwork`. You can only pull from upstream, not push.

It seems like people are either pushing to `upstream` or have set the URL to `origin` incorrectly.

You can update your origin remote url by running:

``` bash
git remote set-url origin <urltoyourfork>
```

**Comment by dbwebconsulting** [comment]
Thanks for the clarification.

**Comment by mirkolgt** [comment]
I have the same problem. I think though is driven by the fact that I "logged" in with a different account. How do I sign out and back in with the "correct" Github account from terminal?
Thanks!

**Comment by satheesh-mallow** [comment]
I too have an same problem. Where am using the same account but in different mac.

While pushing to orgin from my office it throwing an error.

remote: Permission to satheeshmech/satheesh.git denied to SwathiVishwa. fatal: unable to access 'https://github.com/satheeshmech/satheesh.git/': The requested URL returned error: 403

**Comment by vadivelanproz** [comment]
pushing to remote orgin it throwing an error
fatal: unable to access 'https://github.com/demo.git/': The requested URL returned error: 403

**Comment by PHPERHUANGSIR** [comment]
me too,how to solve?

**Comment by huyong007** [comment]
first>git  pull...
then>git push...

**Comment by csvhub** [comment]
I have a same problem. When I commit and push to remote it throwing an error " Permission to hpcity/hoangsa-library.git denied to TruongVanHa."
 How to fix it?

**Comment by Silatibebe** [comment]
i have same issue 
/workspace/hello-world/patchwork (gh-pages) $ git push origin mypatch_test
remote: Permission to jlord/patchwork.git denied to Silatibebe
fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403

**Comment by kosemani2** [comment]
I have the same error, though it seems I typed a wrong password. I thought I should be prompted to re-enter my password each time try to push changes to my origin via bash. But I keep getting the same error over and over. Kindly help with a way out anybody?

remote: Permission to kosemani2/gitlearning.git denied to kosemani1.
fatal: unable to access 'https://github.com/kosemani2/gitlearning.git/': The requested URL returned error: 403

**Comment by sravanpsk** [comment]
#

**Comment by pmndifon** [comment]
SOLVED HERE! https://stackoverflow.com/questions/15381198/remove-credentials-from-git

**Comment by shivkg** [comment]
thanks i have resolved

**Comment by nacongodev** [comment]
clone from a fork project instead of the master project

**Comment by jeanmonse16** [comment]
@jlord thank you for your explanation !! it was exactly what was happening to me

**Comment by neocodegh** [comment]
I solved this error after the leader of the group in which i was contributing sent me an invitation to join as a collaborator. Hence if you are collaborating in a group and you encounter the same issue then please alert your leader to send you an invitation. Hope it helps!

**Comment by NandoRosero** [comment]
Saludos, tengo el mismo problema:

$ git push -u origin develop
remote: Permission to landetaedwin/sitp-app.git denied to NandoRosero.
fatal: unable to access 'https://github.com/landetaedwin/sitp-app.git/': The requested URL returned error: 403

**Comment by Kumarbek9292** [comment]
remote: Permission to Kamil-Esh/our-project-fixed.git denied to Kumarbek9292.
fatal: unable to access 'https://github.com/Kamil-Esh/our-project-fixed/': The requested URL returned error: 403

**Comment by sandeep8854** [comment]
hi hello..
some problem
remote: Permission to sandeep8854/FirstGitHubCommandLineProj.git denied to Kuldeep8853.
fatal: unable to access 'https://github.com/sandeep8854/FirstGitHubCommandLineProj.git/': The requested URL returned error: 403

**Comment by adilshehzad786** [comment]
This command works for me 
`git push -u origin main --force`

i am using main as my branch You can change with respective to your branch

**Comment by surajsgh** [comment]
First, Delete your generic credentials (Google it!) and after that run the command 'git push -u origin main'.
You'll see a popup that'll ask you to connect the browser to your github account or something like that. 
After that run the following commands:
git pull
git push -u origin main.

**Comment by Rakib221** [comment]
remote: Permission to rakib221PS/somePorblemSolving.git denied to Rakib221.
fatal: unable to access 'https://github.com/rakib221PS/somePorblemSolving.git/': The requested URL returned error: 403

I have 2 git hub account. That's why this problem has happened. Please help me.

**Comment by raushan6760** [comment]
hey i faced same problem but this problem appear when you use two account, so remove one account. watch this video to remove https://youtu.be/b5CQ6XdEGxg account after that you can fresh sign in. i hope it will help you a lot
