### ISSUE TITLE
awaiting reperobot's response

### ISSUE THREAD

**Issue by dboeke** [jlord/patchwork#11709]
@jlord I have tried adding reporobot as a contributor several times, but the status continues to say "awaiting reperobot's response", and when I run the tests in git-it, i get "Reporobot doesn't have access to the fork"

https://github.com/dboeke/patchwork/settings/collaboration

Help?

**Comment by jlord** [comment]
Unfortunately some changes to repository invites on GitHub.com have broken this part of Git-it. I opened an issue on Git-it: https://github.com/jlord/git-it-electron/issues/137 but will duplicate it here in this repository as well. 

The rest of the challenges will still work and one can still complete Git-it, the collaboration challenge will have to be skipped for now until a fix is made.
