### ISSUE TITLE
NOTICE: Changes to GitHub.com have broken some parts of @reporobot

### ISSUE THREAD

**Issue by jlord** [jlord/patchwork#11760]
@reporobot has many jobs, one of them is to write to your repo so that you collaborate and pull in changes. 

This part is now broken because of a change to GitHub.com where you must click a button to accept becoming a collaborator in a project rather than be automatically added as it was previously. 

Thus this part of Reporobot is broken. Since it can't yet accept the invite it can't write to your repo and you can't pull in the changes.

Thus Git-it can't verify the challenge checking that you added it to your repo.

**But!** You can keep going!
### Skip It's a Small World and Pull Never Out of Date and go on to Requesting You Pull Please.

Reporobot can still merge your PR and add you to the list ✨ 

🔗 https://github.com/jlord/git-it-electron/issues/137
:link: https://github.com/jlord/reporobot/issues/30

**Comment by gontadu** [comment]
Somehow, when I did this last night... I saw that the invite part was pending, but it still marked all the challenges as completed. Did not need to skip. This leads me to believe that something was fixed on the code side.

**Comment by derozic** [comment]
It worked fine for me....

**Comment by ghost** [comment]
Did your pull request get added from "Requesting you pull, please"?

**Comment by jlord** [comment]
Fixed 🎉 https://github.com/jlord/reporobot/pull/31
