### ISSUE TITLE
please help me please!

### ISSUE THREAD

**Issue by YuJinchi** [jlord/patchwork#12675]
I sent the request to the reporobot.
How long I will wait for?
https://github.com/YuJinchi/patchwork/invitations
thank you
@jlord

**Comment by jlord** [comment]
There has been an update to GitHub which broke this feature. I hope to fix it soon but in the meantime, unfortuantely, this particular challenge is blocked, but you can still finish the rest of Git-it.

See this issue https://github.com/jlord/patchwork/issues/11760
