### ISSUE TITLE
My did my PR #1680 not merge?

### ISSUE THREAD

**Issue by samjewell** [jlord/patchwork#1681]
Hey @jlord 

Sorry to bother you - can't understand why Reporobot thinks I have too many files? I've added you as a contrib to my repo, in case that helps.

https://github.com/jlord/patchwork/pull/1682

Thanks a lot in advance, Otherwise I think Git-it is incredible, and would love to contribute (more than just my name even) - thanks! Sam

**Comment by jlord** [comment]
Wow—so weird. The first commit you have on your branch is from June and from @reporobot when it should be yours... I'm not sure how that happened. You forked it 4 days ago?

It's looking like Reporobot is having trouble right now and I don't have time right now to dig into it, but I can hopefully get into it soon!

**Comment by samjewell** [comment]
I deleted everything and started again, doing everything in a single sitting, and managed to complete it
:-D
So gonna close my issue :-)
