### ISSUE TITLE
Question about reporobot

### ISSUE THREAD

**Issue by gsuxlzt** [jlord/patchwork#17746]
hi @jlord. Is it possible to add reporobot as a collaborator again even after it has already pushed the name art? I am getting an error in verifying the PULL NEVER OUT OF DATE exercise, even if the reporobot has already pushed the art, so I thought of starting it all over again (deleting the repo clone and then cloning again). However, the reporobot has still not accepted my invitation to collaborate. Thanks a lot!

**Comment by jlord** [comment]
Hmm, I'm not sure off the the top of my head but you can still skip ahead to the other challenges and still complete it :)

But I'll look into this when I get a chance 👍

**Comment by gsuxlzt** [comment]
Okay. I'll do that instead. Thanks a lot. I'll close this issue now.
