### ISSUE TITLE
Reporobot doesn't update my file in the contributors folder

### ISSUE THREAD

**Issue by woj-sierak-hmh** [jlord/patchwork#1824]
I'm currently in the Pull Never Out Of Date step and I've followed all of the previous steps, add-wsihmh is added to the contributors folder in my add-wsihmh branch, the reporobot is added as a contributor. The problem is that i don't see any changes in my remote repository when doing pull. Is the robot on holidays at the moment?

**Comment by jlord** [comment]
Haha, no he's not on holidays, but I'm also not sure why he's slacking off! Digging into it now/this weekend!

**Comment by jlord** [comment]
I did a bunch of fixing and test writing to @reporobot and this should be fixed now :tada:

**Comment by woj-sierak-hmh** [comment]
thanks
