### ISSUE TITLE
Final step in Merge Tada! not verifying

### ISSUE THREAD

**Issue by benji1304** [jlord/patchwork#2077]
I've been going through each step, all going fine until i get to the very last step to verify the final part and I have the following

ACTUAL                             EXPECTED

---

"Branch has been merged!"          "Branch has been merged!"
"Uh oh, branch is still there." != "Branch deleted!"
""                                 ""
# FAIL

I can't find the branch that hasn't been deleted?

**Comment by jlord** [comment]
Closing here, issue at https://github.com/jlord/git-it/issues/138
