### ISSUE TITLE
Contributors folder not found

### ISSUE THREAD

**Issue by breindy** [jlord/patchwork#21896]
I'm trying to do "Branches aren't just for birds" but I cant find the contributors folder on my branch or on the original repo. Can anyone help me

**Comment by jlord** [comment]
Hiya!

Sorry about that, it got erased for some reason. I've just added it back though 👍 

You pull in the update with from the `gh-pages` branch of your cloned copy (then you can create a new `add-breindy` branch:

```bash
git pull upstream gh-pages
```

Or re-fork and clone.

**Comment by breindy** [comment]
Wait so, I go on my `gh-pages` branch and `git pull upstream gh-pages` but I still don't see the Contributor's folder. Am I doing something wrong?

**Comment by Evermeij** [comment]
Can't find the contributors folder either

**Comment by miku86** [comment]
create the folder yourself and you will pass

**Comment by eldf7** [comment]
Yeah. I'm creating the contributors folder myself too

**Comment by jotek-io** [comment]
Not sure if this is the same exact issue but I had problems passing as well. The folder was there but everything is case sensitive on linux (as mac and win are not). The folder is named 'C'ontributors on the branch. It needs to be 'c'ontributors, so it couldn't verify the folder. Just change the C -> c and it passes!

**Comment by jlord** [comment]
Thanks @upRos3! That made it super clear ✨ 

I've just updated this repo to have a lowercase C `contributors` directory now which should solve this issue. 

Please re-open if it doesn't 👍
