### ISSUE TITLE
Contributors Folder Too Large to Find Your Contribution

### ISSUE THREAD

**Issue by jlord** [jlord/patchwork#2970]
:link: https://github.com/nodeschool/discussions/issues/962

**Comment by shivankD** [comment]
I see this issue has been quiet for a while, but I'd just like to submit an alternate idea - can we have all the contributors in subfolders based on the starting letter of their usernames? so, someone like me would belong to contributors/s/shivankD? I can write up a script to do it and then submit it to this repo. Later on @reporobot can work its magic automatically?

**Comment by jlord** [comment]
Closed with #11171
