### ISSUE TITLE
Forked repository patchworks won't work as a github.io page

### ISSUE THREAD

**Issue by aomont** [jlord/patchwork#418]
Hi Jessica, 

I just completed the git-it challenges, and as a result I have forked the patchwork repo (here : https://github.com/arthuroo/patchwork). 
However, it won't show up as a github.io website (http://arthuroo.github.io/patchwork sends back a 404 error message...)
Is that normal behavior, and, if yes, how come? I can't figure it out, given that my repo has a gh-pages branch, and that apart from that it's a perfect copy of your master repo... My only idea was that maybe forked repos don't work for github.io websites, would that be it?

Also, I'll take advantage of posting here to thank you for git-it, it was an awesome learning tool!

Cheers!

Arthur

**Comment by jlord** [comment]
Hi, Arthur! 

Forked repos with webfiles on a `gh-pages` branch will also become hosted sites on the forkees (is that a word?) account, but you must make one commit on the `gh-pages` branch for it to become live. They're not hosted by default, only when the forked one starts getting use, if that makes more sense.

So just make a commit, doesn't matter how small, and it should work! :octocat:

**Comment by aomont** [comment]
Oh yes, that makes a lot of sense actually.

And it worked just fine! For anyone who might have the same issue, it did take about 10/15 minutes for the page to show up after the first commit, but it did.

Thanks a lot Jessica!

**Comment by jlord** [comment]
Awesome!
