### ISSUE TITLE
hi there sorry to bother, it seems like i have completed the assesments correctly but my name aint showing up on the final website, can you help me to see where i screwed?

### ISSUE THREAD

**Issue by AlexanderTovMtz** [jlord/patchwork#44953]
**NOTE** I do not get notifications for new issues created in this repository (because there are so many PRs coming through as people do the challenges it would flood my inbox) so if you open an issue you must ping me, @jlord. 

Also please consider if your issue is actually with [Git-it](https://github.com/jlord/git-it-electron) or [reporobot](https://github.com/jlord/reporobot) as this repository is generated by those two.

**Comment by hudsontrius80A** [comment]
[12031998-4.pdf](https://github.com/jlord/patchwork/files/8587931/12031998-4.pdf)
