### ISSUE TITLE
Where's the Art Show?

### ISSUE THREAD

**Issue by SpencerStreibel** [jlord/patchwork#7184]
Small issue, but I was interested in repo robot's art and was crushed to see he didn't make an artistic interpretation of my name :cry: I couldn't find documentation for it and it seemed like there were a number of other scattered people who didn't receive the file edit.

**Comment by SpencerStreibel** [comment]
I suppose a tag would've been smart -.-
@jlord

**Comment by faraixyz** [comment]
Hey @SpencerStreibel. It seems to add some new names to the <code>contributors</code> folder.

**Comment by jlord** [comment]
Not sure why @reporobot may skip some names (it is intended to do all :grin:) but it uses the [asciify](https://www.npmjs.com/package/asciify) module to draw the names :art:
