### ISSUE TITLE
Pull Request Instructions

### ISSUE THREAD

**Issue by mikegomezg** [jlord/patchwork#7554]
In order for the pull request to work, don't you have to first push the changes you made to your local repository up to your remote branch? Then you initiate a pull request to jlord/gh-pages. Otherwise GitHub doesn't see any changes to pull in.

I only mention this because it doesn't seem like that push step was in the directions. But maybe that's not the only way to do it.

**Comment by jlord** [comment]
Hi!

You're right you need to push local changes to the remote. This is a part of the "Branches..." challenge in Git-it: http://jlord.us/git-it/challenges/branches_arent_just_for_birds.html.

After pushing changes in this step @reporobot adds his changes to the remote branch so when it is time to make your pull request the remote branch is up to date.
