### ISSUE TITLE
Unable to push my branch - Tutorial  "BRANCHES AREN'T JUST FOR BIRDS" failed

### ISSUE THREAD

**Issue by ksngits** [jlord/patchwork#7649]
ksngits:~/workspace/patchwork/contributors (ksngits) $ git-it verify
Verifying "BRANCHES AREN'T JUST FOR BIRDS"...

ACTUAL                             EXPECTED

---

"Branch name expected: add-ksngits" != "Found branch as expected!"  
"{ [Error: Command failed: /bin/sh -c git reflog show origin/ksngits" != "Changes have been pushed!"  
"fatal: ambiguous argument 'origin/ksngits': unknown revision or path not in the working tree." != "File in contributors folder!" 
"Use '--' to separate paths from revisions, like this:" != ""  
"'git <command> [<revision>...] -- [<file>...]'" != null  
"]"                             != null  
"  killed: false,"              != null  
"  code: 128,"                  != null  
"  signal: null,"               != null  
"  cmd: '/bin/sh -c git reflog show origin/ksngits' }" != null  
""                              != null                           
# FAIL

Your solution to BRANCHES AREN'T JUST FOR BIRDS didn't match the expected output.

**Comment by AJaramillo54** [comment]
I also receive this error using GitHub for Windows.

**SOLVED** I hadn't run through GET GIT and GITHUBBIN, as I already had a GitHub account. Running through them solved the issue.

**Comment by Baltimorejones** [comment]
I'm receiving the following error: the requested url returned error: 403
fatal: unable to access 'https://github.com/jlord/pathwork.git/': The requested URL returned error: 403

**Comment by ghost** [comment]
@Baltimorejones problably you already solve this problem but mayby not... its PATCHWORK not PATHWORK like in your URL, so it's should be https://github.com/jlord/patchwork.git

**Comment by jlord** [comment]
If anyone is still having trouble with this, please open an issue at the [new repo for Git-it](https://github.com/jlord/git-it-electron) ✨

**Comment by bitakazemi** [comment]
I get the same error
remote: Permission to jlord/patchwork.git denied to bitakazemi.
fatal: unable to access 'https://github.com/jlord/patchwork/': The requested URL returned error: 403

**Comment by tianhang** [comment]
I get the same error
remote: Permission to jlord/patchwork.git denied to bitakazemi.
fatal: unable to access 'https://github.com/jlord/patchwork/': The requested URL returned error: 403

**Comment by jlord** [comment]
If you get this error then you are trying to push to the wrong branch. You should be pushing your changes to _your_ branch on your fork, not the original. If `/jlord/` is in the URL path then it is not going to your account, which is why you get the 403 and are unable to access. 

You can see what remotes you have set up and their addresses with: 

```
git remote -v
```

Check that you are pushing your changes to the correct place.

I will update the tips at the bottom of the challenge for this 👍

**Comment by zouhairkhallaf** [comment]
1- If you are in this forlder: /usr/local/git-it/patchwork/contributors
2- Go back up one step using (means to: /usr/local/git-it/patchwork) using cd ..
3- do : $ git add -A 
4- check your: $ git status
5- You will git this message 
      On branch add-YOURBRANCHNAME      
      nothing to commit, working tree clean
6- $ git commit -m "YOUR MESSAGE"
       On branch add-YOURBRANCHNAM
       nothing to commit, working tree clean
7- NOW DO THIS : $ git push --set-upstream origin add-YOURBRANCHNAME
This should fix it : here is the output 
bash-3.2# git push --set-upstream origin add-YOURBRANCHNAME
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (11/11), 932 bytes | 0 bytes/s, done.
Total 11 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 2 local objects.
To https://github.com/YOURUSRNAME/patchwork
 * [new branch]      add-YOURBRANCHNAME -> add-YOURBRANCHNAME
Branch add-YOURBRANCHNAME set up to track remote branch add-YOURBRANCHNAME from origin.
bash-3.2# git-it verify
ALL SHOULD BE AS GREEN AS THE DOLLAR BILLS

**Comment by NinemillaKA** [comment]
still the same error
