### ISSUE TITLE
Reporobot thinks my branch name doesn't have 'add-' but I think it does

### ISSUE THREAD

**Issue by hmor100** [jlord/patchwork#8021]
I couldn't finish the last step of the tutorial. Reporobot says my branch name is wrong and will not allow me to submit a pull request to this repository against my add-hmor100 branch. I followed the instructions to add the 'add-' again to the name but it should already be there and this has not been working.

$ git branch -m add-hmor100
$ git push origin add-hmor100

$ git branch -m add-HMOR100
$ git push origin add-HMOR100

Do you have any ideas how I can complete the last step?

Thanks!

**Comment by jlord** [comment]
Hiya!

I'm not sure I understand your question correctly but the pull request from your branch can be made and here's a link to get it started:

https://github.com/jlord/patchwork/compare/gh-pages...hmor100:add-hmor100?expand=1

Your branch name and file name look good so hopefully it goes through :sparkles:
