### ISSUE TITLE
Too big for the GitHub API

### ISSUE THREAD

**Issue by jlord** [jlord/patchwork#8613]
As of Jan. 11th the `index.html` file became over 1MB and too large to use with the GitHub API so it is not being rebuilt with new names (though new names are still being collected). There are a few options:
- Use the Git Data API
  - Pro: don't have to worry about size in future
  - Potential Con: Ahh, use Git Data API 
- Render the page client-side
  - Pro: don't get limited by API
  - Potential Con: slow website loading lots of elements
    - [ ] test this out
- ~~Use Jekyll~~
  - ~~Pro: Jekyll does the hefty lifting, don't get limited by API~~
  - ~~Con: users can't view the site themselves without knowing Jekyll~~
- Only show last 100 or 200 names (_leaning towards this option_)
  - Pro: File stays small
  - Con: Everyone's name isn't there forever, but this is probably just a small con.

**Comment by M1kep** [comment]
So currently where is it failing?

**Comment by jlord** [comment]
@M1kep I went through my server logs and found where it was failing and where I got the response from GitHub that the file was too big and to use the Git Data API. The file currently using the regular API—

> https://github.com/jlord/reporobot/blob/master/buildpage.js

I'm adding another option to the list up above which is to just how the last 100 or 200 on the page rather than _all_. I'm guessing not many come back to see their name in the list and so long as we have the number of all who have completed it, it should still feel impactful. I'm leaning towards this option now.

**Comment by jlord** [comment]
Woot, page is back up and fixed now :sparkles: :pizza:

**Comment by thegerscheffect** [comment]
is it possible to only show the newest additions in contributors folder?

**Comment by jlord** [comment]
@thegerscheffect Yep, that's what it does now, it just shows the last 100—http://jlord.us/patchwork
