### ISSUE TITLE
Can you please remove add-bitgrower.txt to contributors?

### ISSUE THREAD

**Issue by bitgrower** [jlord/patchwork#9042]
Thank you ... 

I'm trying to finish git-it -- and I didn't realize how to advance thru the lessons .. thus I was doing the lessons without getting credit for doing them.

When I went back to re-do them, this caused problems with my add-bitgrower.txt file...

I'm sure there's a way to fix this using git from my accesses, but that's a bit beyond my current git/github "paygrade" ... 

Thanks!!!!

**Comment by jlord** [comment]
It's gone now 👍
